FROM scratch

LABEL maintainer Kevin Wiesmueller <kwiesmueller@seibert-media.net>
LABEL type "public"
LABEL versioning "simple"

ARG TOOL

ADD ./build/ /
COPY files/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt

ENTRYPOINT ["./app"]
